### ISSUE TITLE
Bug Report: Hamburger Menu Not Disappearing on Link Selection

### ISSUE THREAD

**Issue by PatelKaran0104** [PatelKaran0104/Movie-Website#1]
**Issue**  
When selecting a link from the hamburger menu, the menu remains open instead of disappearing as expected.

**Steps to Reproduce**  
1. Open the [Cinemascopes website](https://cinemascopes.netlify.app/) on a mobile or narrow screen.
2. Click on the hamburger menu to open it.
3. Select any link from the menu.

**Expected Behavior**  
The hamburger menu should close upon selecting a link, navigating to the selected page.

**Actual Behavior**  
The menu remains open even after a link is selected, requiring the user to manually close it.

**Environment**  
- Website: [Cinemascopes](https://cinemascopes.netlify.app/)
- GitHub Repository: [Movie Website](https://github.com/PatelKaran0104/Movie-Website)

**Suggested Fix**  
Consider adding an event listener to close the menu upon link selection.

**Comment by lhtoan** [comment]
Hello, This is my first time working with open source. Can I try to solve this issue? Thank you!

**Comment by PatelKaran0104** [comment]
> Hello, This is my first time working with open source. Can I try to solve this issue? Thank you!

Yes, sure give it a go, also a heads up you don't need to configure the api key its hard coded for the time being just clone the repo and run it. It should work.

**Comment by lhtoan** [comment]
> > Hello, This is my first time working with open source. Can I try to solve this issue? Thank you!
> 
> Yes, sure give it a go, also a heads up you don't need to configure the api key its hard coded for the time being just clone the repo and run it. It should work.

Can you check if I have handled this error correctly? 
https://github.com/lhtoan/Movie-Website
Because this is my first time, if there is anything wrong please give me your feedback. Thank you!

**Comment by PatelKaran0104** [comment]
Thanks the issue is fixed!!!
